#!/usr/bin/env bash

set -e # Exit on error

find . -name "BUILD.bazel" \
  | xargs yarn buildifier --lint=warn --mode=check --warnings=all
yarn buildifier --lint=warn --mode=check --warnings=all WORKSPACE
