#!/usr/bin/env bash

set -e # Exit on error

# Install buildifier via  
# go install github.com/bazelbuild/buildtools/buildifier@latest
find . -name "BUILD.bazel" -not -path "./node_modules/*" \
  | xargs buildifier --lint=fix --mode=fix --warnings=all
buildifier --lint=fix --mode=fix --warnings=all MODULE.bazel
